name: widget_size
description: A widget to calculate it's size after being built and attached to a widget tree
version: 0.0.4
homepage: https://github.com/javaherisaber/widget_size

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
